/** @format */

import { Outfit } from 'next/font/google'
import './globals.css'

import Providers from './components/provider'
// import ThemeSwitcher from './components/themeSwitcher'
import Navbar from '@/app/components/layout/navbar'
import Footer from '@/app/components/layout/footer'

const outfit = Outfit({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html
      lang='en'
      suppressContentEditableWarning
    >
      <body
        className={`bg-white text-black dark:bg-[#1E1E1E] dark:text-[#FFFEF2] ${outfit.className}`}
      >
        <Providers>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
